apiVersion: v1
kind: ServiceAccount
metadata:
  name: springboot-operator-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # 这里指定角色名称为 springboot-operator-admin
  name: springboot-operator-admin
rules:
  # 权限规则：允许所有资源的所有操作,
  #         生产环境需要做好权限控制, 只保留关键资源的监控和操作
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: springboot-operator-admin-binding
subjects:
  - kind: ServiceAccount
    name: springboot-operator-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: springboot-operator-admin
  apiGroup: rbac.authorization.k8s.io